#!/bin/bash

#---
## Check number of arguments
#---
if [ "$#" -ne 1 ]; then
	echo "Usage: readme [github|gitlab]:user/repository"
	exit
fi

#---
## Split arguments
#---
LIST=$(echo $1 | tr ":" "\n")
ARGS=()
for seg in $LIST
do
	ARGS+=($seg)
done

LINK=$(echo ${ARGS[1]} | tr "/" "-")

#---
## If it's github
#---
if [ ${ARGS[0]} = 'github' ]; then

	#---
	## Check if you already downlaod the README
	#---
	if [ -f ~/.docky/$LINK/README.md ]; then
		mad ~/.docky/$LINK/README.md
	#---
	## If not, download it
	#---
	else
		RESPONSE=$(wget -q "https://raw.githubusercontent.com/${ARGS[1]}/master/README.md" -P ~/.docky/$LINK)
        	mad ~/.docky/$LINK/README.md
	fi

#---
## If it's gitlab
#---
elif [ ${ARGS[0]} = 'gitlab' ]; then

	#---
        ## Check if you already downlaod the README
        #---
	if [ -f ~/.docky/$LINK/README.md ]; then
                mad ~/.docky/$LINK/README.md
        #---
        ## If not, download it
        #---

	else
                RESPONSE=$(wget -q "https://gitlab.com/${ARGS[1]}/raw/master/README.md" -P ~/.docky/$LINK)
                mad ~/.docky/$LINK/README.md
        fi

fi
